### ISSUE TITLE
An application must contain one web cartridge

### ISSUE THREAD

**Issue by jeffreytu** [daniel-sc/casperjs-cartridge#1]
Hello. Thank you for putting together this cartridge. 

It might be just me being new to OpenShift but I'm having trouble creating my app with the custom cartridge you provided. Can you point me in the right direction? Thanks.

```
$ rhc app-create aim https://raw.githubusercontent.com/daniel-sc/casperjs-cartridge/mast
er/metadata/manifest.yml
DL is deprecated, please use Fiddle
The cartridge
'https://raw.githubusercontent.com/daniel-sc/casperjs-cartridge/master/metadata/manifest.yml'
will be downloaded and installed

Application Options
-------------------
Domain:     aimnotifier
Cartridges: https://raw.githubusercontent.com/daniel-sc/casperjs-cartridge/master/metadata/manifest.yml
Gear Size:  default
Scaling:    no

Creating application 'aim' ...
An application must contain one web cartridge. None of the specified cartridges is a web
cartridge. Please include one of the following cartridges: diy-0.1, jboss-dv-6.0.0,
jboss-unified-push-1, jboss-vertx-2.1, jboss-wildfly-8, jbossas-7, jbosseap-6,
jbossews-1.0, jbossews-2.0, jenkins-1, nodejs-0.10, nodejs-0.6, perl-5.10, php-5.3,
php-5.4, python-2.6, python-2.7, python-3.3, ruby-1.8, ruby-1.9, ruby-2.0, zend-5.6, and
zend-6.1 or supply a valid url to a custom web_framework cartridge.
```

**Comment by daniel-sc** [comment]
Hi @jeffreytu 

To my knowledge: The casperjs cartrigde cannot be used 'stand alone'. I.e. you want to install some stand alone- (a.k.a web-) cartridge and then add the casperjs cartridge to that application. Does that make sense and works for you? (You are very welcome to contribute and convert this cartridge to a stand alone/web version!)

Just found a link: http://www.openshift.org/documentation/oo_cartridge_developers_guide.html (appearently correct terminology is 'embedded' and 'primary' cartridge).
