### ISSUE TITLE
PhantomJS crashes on OpenShift when using phantomjs-node

### ISSUE THREAD

**Issue by airscendant** [daniel-sc/casperjs-cartridge#2]
Hi there. I've installed PhantomJS and the sgentle NPM module (https://github.com/sgentle/phantomjs-node/wiki) on Mac OS X and it works as expected in a Node script:

var phantom = require('phantom');
phantom.create(function (ph) {
  // code removed for server, works locally
});

Next I installed your cartridge onto an existing NodeJS app in OpenShift. The Casper and Phantom environment worked, echoing the version successfully. However even with the simplistic code above, this error is thrown:

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EACCES
    at errnoException (net.js:905:11)
    at Server._listen2 (net.js:1024:19)
    at listen (net.js:1065:10)
    at net.js:1147:9
    at asyncCallback (dns.js:68:16)
    at Object.onanswer [as oncomplete](dns.js:121:9)
DEBUG: Program node server.js exited with code 8

I'm assuming from googling that I need to set the options for Phantom, but how do I get these from the OpenShift environment? For example, setting the path to "/var/lib/openshift/xxxxxxx/casperjs/phantomjs/bin/" doesn't make any difference. How about IP address and port? Any other ideas? Is there a better NodeJS module for using your cartridge?

**Comment by daniel-sc** [comment]
Hi - never tried the node-js cartrdige, but looking at https://github.com/sgentle/phantomjs-node#use-it-in-restricted-enviroments it looks to me, like something like

``` javascript
var options = {
  port: process.env.OPENSHIFT_NODEJS_PORT,
  hostname: process.env.OPENSHIFT_NODEJS_IP,
  path: process.env.PHANTOMJS_EXECUTABLE
}

phantom.create(function, options);
```

should solve the issue - does it?

Maybe you need to extract the folder from `PHANTOMJS_EXECUTABLE` - or create a new environment variable pointing to the folder of the phantomjs executable instead of the executable itsself (pull request welcome!).

See also: https://developers.openshift.com/en/managing-environment-variables.html

**Comment by thomaswb** [comment]
Thanks, Daniel. That pointed me in the right direction. Defining the port conflicts with the express server, ("address in use" error) and the path needs to be the directory, not the executable, so in the end I found this to work:

``` javascript
var options = {
  hostname: process.env.OPENSHIFT_NODEJS_IP,
  path: require('path').dirname(process.env.PHANTOMJS_EXECUTABLE) + '/'
}
```

Thanks again for your rapid response!

**Comment by daniel-sc** [comment]
Glad I could help!
